import uuid
from datetime import date, datetime

from sqlalchemy import CHAR, Boolean, Date, DateTime, Numeric, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Vendor(Base):
    __tablename__ = "vendors"

    id: Mapped[str] = mapped_column(CHAR(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    service_type: Mapped[str] = mapped_column(String(150), nullable=False, default="General")
    contact_person: Mapped[str | None] = mapped_column(String(150))
    email: Mapped[str | None] = mapped_column(String(150))
    contact_number: Mapped[str | None] = mapped_column(String(50))
    address: Mapped[str | None] = mapped_column(Text)
    gst_number: Mapped[str | None] = mapped_column(String(100))
    licence_url: Mapped[str | None] = mapped_column(Text)
    certificate_url: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(50), default="Active", server_default="Active")
    vendor_code: Mapped[str | None] = mapped_column(String(100))
    vendor_category: Mapped[str | None] = mapped_column(String(150))
    business_name: Mapped[str | None] = mapped_column(String(255))
    mobile_number: Mapped[str | None] = mapped_column(String(50))
    alternate_mobile_number: Mapped[str | None] = mapped_column(String(50))
    website: Mapped[str | None] = mapped_column(String(255))
    whatsapp_number: Mapped[str | None] = mapped_column(String(50))
    address_line_1: Mapped[str | None] = mapped_column(Text)
    address_line_2: Mapped[str | None] = mapped_column(Text)
    city: Mapped[str | None] = mapped_column(String(100))
    state: Mapped[str | None] = mapped_column(String(100))
    country: Mapped[str | None] = mapped_column(String(100))
    zip_code: Mapped[str | None] = mapped_column(String(50))
    pan_number: Mapped[str | None] = mapped_column(String(50))
    registration_number: Mapped[str | None] = mapped_column(String(100))
    license_number: Mapped[str | None] = mapped_column(String(100))
    trade_license_number: Mapped[str | None] = mapped_column(String(100))
    years_of_experience: Mapped[int | None] = mapped_column()
    available_days: Mapped[str | None] = mapped_column(Text)
    working_hours: Mapped[str | None] = mapped_column(String(100))
    emergency_service: Mapped[bool | None] = mapped_column(Boolean)
    support_24_7: Mapped[bool | None] = mapped_column(Boolean)
    contract_start_date: Mapped[date | None] = mapped_column(Date)
    contract_end_date: Mapped[date | None] = mapped_column(Date)
    contract_value: Mapped[float | None] = mapped_column(Numeric(15, 2))
    payment_terms: Mapped[str | None] = mapped_column(String(255))
    contract_document_url: Mapped[str | None] = mapped_column(Text)
    renewal_reminder: Mapped[bool | None] = mapped_column(Boolean)
    bank_account_name: Mapped[str | None] = mapped_column(String(150))
    bank_name: Mapped[str | None] = mapped_column(String(150))
    bank_account_number: Mapped[str | None] = mapped_column(String(100))
    bank_ifsc_code: Mapped[str | None] = mapped_column(String(50))
    bank_upi_id: Mapped[str | None] = mapped_column(String(100))
    gst_certificate_url: Mapped[str | None] = mapped_column(Text)
    pan_card_url: Mapped[str | None] = mapped_column(Text)
    business_license_url: Mapped[str | None] = mapped_column(Text)
    insurance_certificate_url: Mapped[str | None] = mapped_column(Text)
    agreement_copy_url: Mapped[str | None] = mapped_column(Text)
    identity_proof_url: Mapped[str | None] = mapped_column(Text)
    address_proof_url: Mapped[str | None] = mapped_column(Text)
    other_documents_url: Mapped[str | None] = mapped_column(Text)
    vendor_rating: Mapped[float | None] = mapped_column(Numeric(3, 1))
    preferred_vendor: Mapped[bool | None] = mapped_column(Boolean)
    verified_vendor: Mapped[bool | None] = mapped_column(Boolean)
    remarks: Mapped[str | None] = mapped_column(Text)
    association_name: Mapped[str | None] = mapped_column(String(255))
    assigned_blocks: Mapped[str | None] = mapped_column(Text)
    assigned_services: Mapped[str | None] = mapped_column(Text)
    assigned_manager: Mapped[str | None] = mapped_column(String(150))
    contact_details_json: Mapped[str | None] = mapped_column(Text)
    services_offered_json: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    is_deleted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default="0")
